// components/work/Details/Row.tsx
import clsx from "clsx";

type RowProps = {
  label: string;
  value: string;
  className?: string;
};

const Row = ({ label, value, className }: RowProps) => {
  return (
    <div
      className={clsx(
        "border-background-muted pl-sm py-xs flex border-b",
        className
      )}
    >
      <span className="text-foreground-muted w-24 shrink-0">{label}</span>
      <span>{value}</span>
    </div>
  );
};

export default Row;

// app/components/work/Row.vue
<script lang="ts" setup>
import { computed } from "vue";

type Props = {
  label: string;
  value: string;
  className?: string;
};

const props = defineProps<Props>();

const rootClass = computed(() => ["pl-sm py-xs flex opacity-0", props.className]);
</script>

<template>
  <div :class="rootClass">
    <span class="text-foreground-muted w-24 shrink-0">{{ label }}</span>
    <span>{{ value }}</span>
  </div>
</template>
