// components/work/Details/RowLabelList.tsx
import clsx from "clsx";

type RowLabelListProps = {
  stack: string[];
  className?: string;
};

const RowLabelList = ({ stack, className }: RowLabelListProps) => {
  return (
    <div
      className={clsx(
        "border-background-muted pl-sm py-xs flex items-start border-b",
        className
      )}
    >
      <div className="text-foreground-muted w-24 shrink-0">Stack</div>
      <div className="gap-xs flex flex-wrap gap-y-0.5 wrap-break-word">
        {stack.map((item, index) => (
          <span key={index}>
						<span>{item}</span>
            {index < stack.length - 1 && <>, </>}
					</span>
        ))}
      </div>
    </div>
  );
};

export default RowLabelList;

// app/components/work/RowLabelList.vue
<script lang="ts" setup>
import { computed } from "vue";

type Props = {
  stack: string[];
  className?: string;
};

const props = defineProps<Props>();

const rootClass = computed(() => ["pl-sm py-xs flex items-start opacity-0", props.className]);
</script>

<template>
  <div :class="rootClass">
    <div class="text-foreground-muted w-24 shrink-0">Stack</div>

    <div class="gap-xs flex flex-wrap gap-y-0.5 wrap-break-word">
      <span v-for="(item, index) in stack" :key="index">
        <span>{{ item }}</span
        ><span v-if="index < stack.length - 1">, </span>
      </span>
    </div>
  </div>
</template>
