// components/work/Details/RowListParent.tsx
import { dm_sans } from "../../../utils/style/fonts/fonts";
import RowList from "./RowList";

type RowListParentProps = {
  description: string[];
  className?: string;
};

const RowListParent = ({ description, className }: RowListParentProps) => {
  return (
    <div>
			<span
        className={`${dm_sans.className} text-foreground-muted pl-sm mt-md block`}
      >
				Highlight
			</span>
      <ul className="pl-sm">
        {description.map((desc, i) => (
          <RowList key={i} desc={desc} />
        ))}
      </ul>
    </div>
  );
};

export default RowListParent;

// app/components/work/RowListParent.vue
<script lang="ts" setup>
import { computed } from "vue";
import RowList from "./RowList.vue";

type Props = {
  description: string[];
  className?: string;
};

const props = defineProps<Props>();

const rootClass = computed(() => [props.className, "opacity-0"]);

const headerClass = computed(() => ["text-foreground-muted pl-sm mt-md block"]);
</script>

<template>
  <div :class="rootClass">
    <span :class="headerClass">Highlight</span>

    <ul class="pl-sm">
      <RowList v-for="(desc, i) in description" :key="i" :desc="desc" />
    </ul>
  </div>
</template>
