// app/components/home/description/Weather.vue
<script lang="ts" setup>
type WeatherUi = { temp: number; condition: string };

const { data } = await useFetch<WeatherUi>("/api/weather", {
  query: { city: "Wiesbaden" },
  server: true,
  lazy: true,
});

const temperature = computed(() => data.value?.temp);
const condition = computed(() => data.value?.condition);
</script>

<template>
  <div v-if="temperature != null && condition" class="flex gap-0.5">
    <span class="text-foreground-muted text-xs">{{ temperature }}°</span>
    <span class="text-foreground-muted text-xs">{{ condition }}</span>
  </div>
</template>

// components/home/Hero/BottomHero/CityInfo/Weather/Weather.tsx
import { dm_mono } from "../../../../../../utils/style/fonts/fonts";

type WeatherData = {
	main: {
		temp: number;
	};
	weather: {
		main: string;
	}[];
};

type WeatherProps = {
	data: WeatherData | null;
};

function Weather({ data }: WeatherProps) {
	if (!data) {
		return null;
	}

	const { weather, main } = data;
	const temperature = Math.round(main.temp);
	const weatherDeg = weather[0].main;

	return (
		<div className="flex gap-1">
			<span
				className={`text-foreground-muted ${dm_mono.className} text-xs uppercase`}
			>
				{temperature}°
			</span>
			<span
				className={`text-foreground-muted ${dm_mono.className} text-xs uppercase`}
			>
				{weatherDeg}
			</span>
		</div>
	);
}

export default Weather;
