// app/components/work/Description.vue
<script lang="ts" setup>
import type { WorkProjectPage } from "~/domain/works/types";

const props = defineProps<{
  work: WorkProjectPage;
}>();
</script>

<template>
  <section class="bg-background text-foreground w-full">
    <div class="flex flex-row gap-12">
      <div class="flex w-1/2 flex-col gap-3">
        <span class="mb-2 block text-xs uppercase">The Project</span>
        <p class="text-4xl">
          {{ work?.description }}
        </p>
      </div>

      <div class="flex flex-col gap-12">
        <div>
          <span class="mb-2 block text-xs uppercase">Role</span>
          <span> {{ work?.role }}</span>
        </div>

        <div v-if="work?.worksDone?.length">
          <span class="mb-2 block text-xs uppercase">Clients</span>
          <ul class="space-y-1.5">
            <li
              v-for="(client, i) in work.worksDone"
              :key="i"
              class="flex items-baseline gap-4 text-sm md:text-base"
            >
              <span class="font-light">{{ client.label }}</span>
            </li>
          </ul>
        </div>
      </div>
      <div class="flex flex-col gap-2.5">
        <span class="mb-2 block text-xs uppercase">Links</span>
        <a
          :href="work.websiteLink"
          class="flex items-center gap-1 text-xs font-bold tracking-widest uppercase underline underline-offset-2 transition-opacity duration-200 hover:opacity-60"
          rel="noopener noreferrer"
          target="_blank"
        >
          Website
        </a>
        <a
          :href="work.linkedinLink"
          class="flex items-center gap-1 text-xs font-bold tracking-widest uppercase underline underline-offset-2 transition-opacity duration-200 hover:opacity-60"
          rel="noopener noreferrer"
          target="_blank"
        >
          Linkedin
        </a>
      </div>
    </div>
  </section>
</template>

// components/Work/Description.tsx
import { FC } from "react";
import { Work } from "../../utils/works";
import Link from "next/link";

interface HeaderProps {
  work: Work;
}

const Description: FC<HeaderProps> = ({ work }) => {
  return (
    <>
      <div className="grid-work-description pt-5 flex flex-col gap-small w-full">
        <span className="pb-medium">
          <Link href="/">{"<"} back home</Link>
        </span>
        <h1 className="heading-regular font-bold">{work.company}</h1>
        <ul>
          {work.description.map((desc) => (
            <li className="list-disc" key={desc}>
              {desc}
            </li>
          ))}
        </ul>
        <ul className="flex flex-col gap-smallest">
          <li className="paragraph text-primary-light">Role: {work.role}</li>
          <li className="paragraph text-primary-light">Date: {work.date}</li>
          <li className="paragraph text-primary-light">Stack: {work.stack}</li>
        </ul>
        <div className="flex flex-col gap-small pt-medium">
          <span>
            <a rel="noopener noreferrer" target="_blank" href={work.linkedin}>
              LinkedIn page {">"}
            </a>
          </span>
          <span>
            <a rel="noopener noreferrer" target="_blank" href={work.website}>
              Website {">"}
            </a>
          </span>
        </div>
      </div>
    </>
  );
};

export default Description;
