// app/components/work/Images.vue
<script lang="ts" setup>
import type { WorkProjectPage } from "~/domain/works/types";

const props = defineProps<{
  work: WorkProjectPage;
}>();
</script>

<template>
  <div class="w-full">
    <div class="flex h-full w-full flex-col gap-5">
      <img
        v-for="(image, index) in work.images"
        :key="image"
        :alt="`${work.name} image ${index + 1}`"
        :src="image"
        class="aspect-video h-fit w-96 object-cover"
      />
    </div>
  </div>
</template>

// components/Work/Images.tsx
import { FC } from "react";
import { Work } from "../../utils/works";

interface HeaderProps {
  work: Work;
}
const Images: FC<HeaderProps> = ({ work }) => {
  if (work.images) {
    return (
      <div className="grid-work-images w-full pt-small">
        <ul className="flex flex-col gap-small">
          {work.images.map((image) => (
            <li key={image}>
              <img src={image} width="1920" height="1109" alt="" />
            </li>
          ))}
        </ul>
      </div>
    );
  } else {
    return null;
  }
};

export default Images;
