// components/HomePage/Time.tsx
import {FC, useEffect, useRef, useState} from "react";
import {gsap} from "gsap";

const Time: FC = () => {
    const [currentTime, setCurrentTime] = useState<string>("");
    const timeRef = useRef<HTMLSpanElement | null>(null);

    useEffect(() => {
        const intervalId = setInterval(() => {
            const today = new Date();
            const time = today.toLocaleTimeString('en-US', {
                hour: '2-digit',
                minute: '2-digit',
                hour12: true,
                timeZone: 'Europe/Rome'
            });
            setCurrentTime(time);
        }, 1000);

        return () => clearInterval(intervalId);
    }, []);

    useEffect(() => {
        gsap.set(timeRef.current, {opacity: 0})
        gsap.timeline().to(timeRef.current, {
            opacity: 0,
            duration: 0.4
        }).to(timeRef.current, {
            opacity: 1,
            duration: 0.4
        })
    }, [currentTime]);

    return <span ref={timeRef}>{currentTime}</span>;
};

export default Time;

// app/components/home/description/Time.vue
<script lang="ts" setup>
import { ref } from "vue";
import { useLiveTime } from "~/composables/useLiveTime";

const timeRef = ref<HTMLElement | null>(null);

const { currentTime } = useLiveTime({
  locale: "it-IT",
  timeZone: "Europe/Rome",
  intervalMs: 1000,
  format: { hour: "2-digit", minute: "2-digit" },
});
</script>

<template>
  <span ref="timeRef">
    {{ currentTime }}
  </span>
</template>
