// app/components/work/RowLinks.vue
<template>
  <div :class="rootClass">
    <span class="text-foreground-muted w-24 shrink-0">Links</span>

    <span class="flex">
      <a
        :href="website"
        class="flex items-center gap-1 underline"
        rel="noopener noreferrer"
        target="_blank"
      >
        <span>Website</span>
      </a>

      <a
        v-if="linkedin"
        :href="linkedin"
        class="flex items-center gap-1 underline"
        rel="noopener noreferrer"
        target="_blank"
      >
        ,<span>LinkedIn</span>
        <ExternalLink />
      </a>
    </span>
  </div>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import ExternalLink from "~/components/global/icons/ExternalLink.vue";

type Props = {
  website: string;
  linkedin?: string;
  className?: string;
};

const props = defineProps<Props>();

const rootClass = computed(() => ["pl-sm py-xs flex opacity-0", props.className]);
</script>

// components/work-project/Details/RowLinks.tsx
import clsx from "clsx";
import SquareArrowOutUpRight from "../../global/Icons/SquareArrowOutUpRight";

type RowLinksProps = {
	website: string;
	linkedin?: string;
	className?: string;
};

const RowLinks = ({ website, linkedin, className }: RowLinksProps) => {
	return (
		<div
			className={clsx(
				"border-background-muted pl-sm py-xs flex border-b-1 opacity-0",
				className,
			)}
		>
			<span className="text-foreground-muted w-24 flex-shrink-0">Links</span>
			<span className="flex">
				<a
					href={website}
					target="_blank"
					rel="noopener noreferrer"
					className="flex items-center gap-1 underline"
				>
					<span>Website</span>
					<SquareArrowOutUpRight />
				</a>
				{linkedin && (
					<a
						href={linkedin}
						target="_blank"
						rel="noopener noreferrer"
						className="flex items-center gap-1 underline"
					>
						,<span>LinkedIn</span>
						<SquareArrowOutUpRight />
					</a>
				)}
			</span>
		</div>
	);
};

export default RowLinks;
