// app/components/work/Images.vue
<script lang="ts" setup>
import type { WorkProjectPage } from "~/domain/works/types";

const props = defineProps<{
  work: WorkProjectPage;
}>();
</script>

<template>
  <div class="w-full">
    <div class="flex h-full w-full flex-col gap-5">
      <img
        v-for="(image, index) in work.images"
        :key="image"
        :alt="`${work.name} image ${index + 1}`"
        :src="image"
        class="aspect-video h-fit w-96 object-cover"
      />
    </div>
  </div>
</template>

// app/crafts/components/Images.tsx
import React, { FC } from "react";

type Image = {
  desktopUrl: string;
  mobileUrl: string;
  alt: string;
  id: number;
  isHorizontal: boolean | null;
};

type ImagesProps = {
  images: Image[];
};

const Images: FC<ImagesProps> = ({ images }) => {
  return (
    <div className="mt-small grid">
      <div className="col-span-full">
        <main className="col-span-full flex flex-wrap gap-small">
          {images.map((image: Image, index: number) => (
            <div
              key={index}
              className={`w-full flex-auto md:w-3/12 ${image.isHorizontal ? " md:w-[58.8%]" : ""}`}
            >
              <img
                src={image.desktopUrl}
                srcSet={`${image.desktopUrl} 2000w, ${image.mobileUrl} 1500w`}
                sizes="(min-width: 66em) 2000px, 1500px"
                fetchPriority={index < 4 ? "high" : "low"}
                loading={index > 4 ? "lazy" : "eager"}
                height="2000"
                width="3000"
                alt={image.alt}
                className="animate-fade-in h-full w-full rounded-lg object-cover object-center"
              />
            </div>
          ))}
        </main>
      </div>
    </div>
  );
};

export default Images;
