// app/components/work/Images.vue
<script lang="ts" setup>
import type { WorkProjectPage } from "~/domain/works/types";

const props = defineProps<{
  work: WorkProjectPage;
}>();
</script>

<template>
  <div class="w-full">
    <div class="flex h-full w-full flex-col gap-5">
      <img
        v-for="(image, index) in work.images"
        :key="image"
        :alt="`${work.name} image ${index + 1}`"
        :src="image"
        class="aspect-video h-fit w-96 object-cover"
      />
    </div>
  </div>
</template>

// components/work-project/Images.tsx
import { FC } from "react";
import { WorkProjectPage } from "../../utils/pages/types";

interface HeaderProps {
  work: WorkProjectPage;
}

const Images: FC<HeaderProps> = ({ work }) => {
  return (
    <div className="w-full">
      <ul className="gap-sm flex w-full flex-col">
        {work.images.map((image, index) => (
          <li key={index} className="w-full">
            <img className="h-full" src={image} loading="lazy" />
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Images;
