// components/global/Navbar/InternalLinks.tsx
import Link from "next/link";
import { usePathname } from "next/navigation";
import { internalRoutes, type LinkItem } from "../../../_config/config";
import works from "../../../utils/data/works";
import { dm_mono } from "../../../utils/style/fonts/fonts";

const InternalLinks = () => {
  const pathname = usePathname();
  return (
    <ul className="gap-md flex items-start">
      {internalRoutes.map((link: LinkItem, index: number) => {
        const isActive =
          link.url === "/" ? pathname === "/" : pathname.startsWith(link.url);
        return (
          <li className="flex" key={link.url}>
            <Link
              href={link.url}
              className={`flex text-xs uppercase ${dm_mono.className} ${
                isActive ? "underline underline-offset-2" : ""
              } ${index !== 1 && index !== 2 ? "mr-1" : ""}`}
            >
              {link.label}
            </Link>
            {index === 1 && (
              <span className="text-foreground-muted ml-1 text-[8px]">
								({works.length})
							</span>
            )}
          </li>
        );
      })}
    </ul>
  );
};

export default InternalLinks;

// app/components/global/navbar/InternalLinks.vue
<script lang="ts" setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { internalRoutes } from '~~/_config/config'

const route = useRoute()
const worksCount = 4

const getLinkStatus = (url: string) => {
  if (url === '/') {
    return route.path === '/'
  }
  return route.path.startsWith(url)
}

const navigationLinks = computed(() =>
  internalRoutes.map((link, index) => ({
    ...link,
    isActive: getLinkStatus(link.url),
    showCount: index === 1,
    hasMargin: index !== 1 && index !== 2,
  })),
)
</script>

<template>
  <ul class="md:gap-md gap-lg flex items-start">
    <li
      v-for="link in navigationLinks"
      :key="link.url"
      class="flex items-baseline"
    >
      <NuxtLink
        :class="[
          link.isActive ? 'underline underline-offset-2' : '',
          link.hasMargin ? 'mr-1' : '',
        ]"
        :prefetch="true"
        :to="link.url"
        class="flex text-xs uppercase font-mono"
      >
        {{ link.label }}
      </NuxtLink>

      <span
        v-if="link.showCount"
        class="text-muted ml-1 text-[8px]"
      >
        ({{ worksCount }})
      </span>
    </li>
  </ul>
</template>
