// app/globalComponents/Navbar.tsx
import { FC } from "react";
import Link from "next/link";
import ThemeToggle from "./ThemeToggle";

export enum NavbarClass {
  FIXED = "fixed",
}

type NavbarProps = {
  navbarClass?: NavbarClass;
};

const Navbar: FC<NavbarProps> = ({ navbarClass }) => {
  return (
    <nav
      className={` ${navbarClass === NavbarClass.FIXED ? "fixed h-fit" : "sm:sticky"} fixed sm:top-3 bottom-3 w-full flex-row-reverse sm:flex-row pr-small pl-small z-10 flex justify-between items-center`}
    >
      <ul className="flex gap-small items-center">
        <li>
          <Link href="/" className="mono">
            Home
          </Link>
        </li>
        <li>
          <Link href="/works" className="mono">
            Works
          </Link>
        </li>
      </ul>
      <ThemeToggle />
    </nav>
  );
};

export default Navbar;

// app/components/global/navbar/Navbar.vue
<script lang="ts" setup>
import InternalLinks from "./InternalLinks.vue";
import ThemeToggle from "~/components/global/navbar/ThemeToggle.vue";
</script>

<template>
  <nav
    class="fixed bg-background bottom-0 left-0 z-30 flex flex-row-reverse md:flex-row w-full items-center justify-between px-sm py-sm md:top-0 md:bottom-auto navbar"
  >
    <NuxtLink class="text-xs text-foreground-muted hidden md:block" to="/"> Ivan Smiths </NuxtLink>
    <InternalLinks />
    <ThemeToggle />
  </nav>
</template>
