// app/components/home/description/Time.vue
<script lang="ts" setup>
import { ref } from "vue";
import { useLiveTime } from "~/composables/useLiveTime";

const timeRef = ref<HTMLElement | null>(null);

const { currentTime } = useLiveTime({
  locale: "it-IT",
  timeZone: "Europe/Rome",
  intervalMs: 1000,
  format: { hour: "2-digit", minute: "2-digit" },
});
</script>

<template>
  <span ref="timeRef" class="text-foreground-muted text-xs uppercase">
    {{ currentTime }}
  </span>
</template>

// components/home/Hero/BottomHero/CityInfo/Time.tsx
import { type FC, useEffect, useRef, useState } from "react";
import { useTextSwap } from "../../../../../utils/hooks/animations/useTextSwap";
import { dm_mono } from "../../../../../utils/style/fonts/fonts";

const Time: FC = () => {
  const [currentTime, setCurrentTime] = useState<string>("");
  const timeRef = useRef<HTMLSpanElement | null>(null);

  useTextSwap(timeRef, currentTime, "");

  useEffect(() => {
    const intervalId = setInterval(() => {
      const today = new Date();
      const time = today.toLocaleTimeString("it-IT", {
        hour: "2-digit",
        minute: "2-digit",
        timeZone: "Europe/Rome"
      });
      setCurrentTime(time);
    }, 1000);

    return () => clearInterval(intervalId);
  }, []);

  return (
    <span
      ref={timeRef}
      className={`text-foreground-muted ${dm_mono.className} text-xs uppercase`}
    >
			{currentTime}
		</span>
  );
};

export default Time;
